### ISSUE TITLE
ImportPresenter

### ISSUE THREAD

**Issue by seri300** [Tim3W4rp/Zatim-ne#21]
Problém byl při programování CSV importu, tak jsem musel udělat novou branch z master větve. Až dokončím CSV tak vložím to do master větve. Nevíte jak spojit master větev z tím co potřebuji.

**Comment by seri300** [comment]
Vkládání do GitHubu jsem udělal s pomocí a děkuji.

**Comment by Tim3W4rp** [comment]
dobře Zdeňku, zavírám issue
