### ISSUE TITLE
Zásek

### ISSUE THREAD

**Issue by Tim3W4rp** [Tim3W4rp/Zatim-ne#7]
Borci měl jsem trochu zásek při generování faktur.
Potřebuju od Míry template, jak pořádně to má vypadat.
A od Toma potřebuju otestovat, jestli správně chodí data.

**Comment by SobikS** [comment]
čus, udělal bych to podobně :) 
[order_20161240.pdf](https://github.com/Tim3W4rp/Zatim-ne/files/614428/order_20161240.pdf)

**Comment by brezovsk** [comment]
čůůs, s Mírou jsme to prošli a všechno chodí tak, jak má.

**Comment by Tim3W4rp** [comment]
Borci super díky moc.
