### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by seri300** [Tim3W4rp/Zatim-ne#9]
Potřeboval bych nějaké podklady na tvorbu dokumentace. Mám jen základní podklady, ale chtělo by to i nějaké podrobnější.

**Comment by SobikS** [comment]
Jakou dokumentaci chces dělat? 👍

**Comment by seri300** [comment]
na CSV import

**Comment by SobikS** [comment]
CSV import z administrace.
Jako je tady - http://osobnivozy.cz/ucet/pridat-inzerat/

**Comment by Tim3W4rp** [comment]
Vyřešeno, zavírám.
